### ISSUE TITLE
Crash with main.py on heatmaps

### ISSUE THREAD

**Issue by swhustla** [swhustla/comparison_of_time_series_methods#155]
Running these cities:
`__list_of_indo_gangetic_plain_cities = ["Ahmedabad",  "Amritsar", "Delhi", "Gurugram", "Lucknow", "Jaipur", "Patna", "Chandigarh", "Kolkata","Guwahati", "Shillong", "Jorapokhar", "Aizawl"]
`

With these methods:
`        "AR",
        "linear_regression",
        "ARIMA",
        "HoltWinters",
        "MA",
        "Prophet",
        "SES",`

I get this error:

`Saving Indian city pollution MAE heatmap plot
Traceback (most recent call last):
  File "/Users/frankkelly/Dropbox/Projects-new/india_air_pollution_study/./main.py", line 298, in <module>
    for list_of_reports in generate_predictions(__methods, __datasets):
  File "/Users/frankkelly/Dropbox/Projects-new/india_air_pollution_study/./main.py", line 265, in generate_predictions
    plot_results_in_heatmap(
  File "/Users/frankkelly/Dropbox/Projects-new/india_air_pollution_study/methods/plot_results_in_heatmap.py", line 35, in draw_plot
    save_plot(figure, dataset_name, chosen_metric)
TypeError: __save_heatmap() missing 1 required positional argument: 'chosen_metric'`

**Comment by swhustla** [comment]
@karukes this may be related to work done with your work on `main_plot.py`?

**Comment by swhustla** [comment]
I've implemented a quick fix to remove the bug in #154 
However, all this code pasted below should be removed from `/methods/...py` and placed in`/plots/....py`. Methods should stay generic and not specific to any dataset.

`for chosen_metric in __chosen_metrics:
            figure = plot_heatmap(data_to_plot, chosen_metric)
            stock_company_name = data_to_plot["subset_row"][0]
            print(f"Saving {dataset_name} {chosen_metric} heatmap plot")
            input_map = {
                ("Stock price", "KO"): (figure, dataset_name, "value", chosen_metric),
                ("Stock price", "AAPL"): (
                    figure,
                    dataset_name,
                    "growth",
                    chosen_metric,
                ),
                ("India city pollution", stock_company_name): (
                    figure,
                    "Indian city pollution",
                    "_",
                    chosen_metric,
                ),
            }
            input_key = (dataset_name, stock_company_name)`


Once it is moved to `/plots/plot_results_in_heatmap.py` it can be called by both methods (from CSV file and from live report).
